# Generated by Django 4.1.5 on 2023-01-29 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyrarian', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tables',
            name='table_id',
        ),
    ]
