# Generated by Django 4.1.5 on 2023-01-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyrarian', '0003_alter_tables_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='columns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=60)),
                ('column_name', models.CharField(max_length=60)),
                ('rogical_name', models.CharField(max_length=60)),
                ('column_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='tables',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
